version: '3.8'

services:
#  copilot_backend:
#    build:
#      context: copilot-backend/
#    container_name: flask-api
#    restart: always
#    ports:
#      - "8000:8000"
#    depends_on:
#      - ollama-api
#    environment:
#      - FLASK_ENV=development
#      - LLAMA_HOST=http://ollama-api:11434  # Corrected for internal Docker network
#
#  copilot_web:
#    build:
#      context: copilot-web/
#    container_name: react-app
##    depends_on:
##      - copilot_backend
#    environment:
#      - FLASK_ENV=development
#      - LLAMA_HOST=http://ollama-api:11434  # Corrected for internal Docker network
#    ports:
#      - "3000:80"
  ollama-api:
    image: ollama/ollama
    container_name: ollama-api
    restart: always
    ports:
      - "11434:11434"
    volumes:
      - ./app_data/ollama_data:/root/.ollama  # Maps host directory to container directory
  chromadb:
    image: chromadb/chroma:latest
    volumes:
      - ./app_data/chroma_db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - PERSIST_DIRECTORY=/chroma/chroma # this is the default path, change it as needed
      - ANONYMIZED_TELEMETRY=${ANONYMIZED_TELEMETRY:-TRUE}
    ports:
      - "9000:8000"

volumes:
  ollama:
    driver: local

networks:
  default:
    driver: bridge
