version: '3.8'

services:
  copilot_backend:
    build:
      context: copilot-backend/
    container_name: flask-api
    ports:
      - "8000:8000"
    environment:
      - FLASK_ENV=development
      - LLAMA_HOST=http://127.0.0.1:11434  # Add this line for external LLaMA service
  copilot_web:
    build:
      context: copilot-web/
    container_name: react-app
    depends_on:
      - copilot_backend
    ports:
      - "3000:80"

networks:
  default:
    driver: bridge
